<a href="https://colab.research.google.com/github/ENG19CS0334-TEJAAL-M/DL_Assignment/blob/main/explore_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**PY TORCH**
https://www.analyticsvidhya.com/blog/2021/04/a-gentle-introduction-to-pytorch-library/


https://youtu.be/RwaVqvZ3xo8

1.PyTorch is an optimized tensor library primarily used for Deep Learining applications using gpu and cpu.

2.Its an open source ML library for Python mainly developed by the Face book AI research team .



In [2]:
import torch

Creating tensors

In [4]:
#tensor with single number
t1=torch.tensor(5.)
print(t1)
t1.dtype

tensor(5.)


torch.float32

In [10]:
#tensor with 1D vector
t2=torch.tensor([1,2,3.,4])
print(t2)
#tebsor with 2d vector
t3=torch.tensor([[1,2,3],[5,6,7]])
print(t3)
# print the shape 
print(t1.shape)# its dimension is 0 since its just a number
print(t2.shape)
print(t3.shape)

tensor([1., 2., 3., 4.])
tensor([[1, 2, 3],
        [5, 6, 7]])
torch.Size([])
torch.Size([4])
torch.Size([2, 3])


Some tensor operations and  computing gradients


In [14]:
#requires_grad indicates whether a variable is trainable. 
x=torch.tensor(3.)
y=torch.tensor(6.,requires_grad=True)
z=torch.tensor(4.,requires_grad=True)
x,y,z
w=x*y+z
print(w)


tensor(22., grad_fn=<AddBackward0>)


AutoGrad

- unique ability of Pytorch which can automatically compute the derivative of any expression

We can observe the following:

* the value of the derivative of w wrt x is** None** as the parameter requires_grad is set to False
* the value of the derivative of y wrt w is 3 as dw/dy = x = 3
* the value of the derivative of y wrt  z is 1 as dw/dz = 1

In [15]:
#Compute derivatives
w.backward()

In [16]:
print("dw/dx =", x.grad)
print("dw/dy =", y.grad)
print("dw/dz =", z.grad)

dw/dx = None
dw/dy = tensor(3.)
dw/dz = tensor(1.)


PyTorch with NumPy
-  Numpy is an opensource library used for scientific and mathematical computing in python
- Numpy has vast supporting libraries such as pandas,opencv,matplotlib

In [19]:
#first create numpy array
import numpy as np
q=np.array([1 ,2 ,3.,4])
print(q)

[1. 2. 3. 4.]


In [26]:
#create a tensor from numpy array
y=torch.from_numpy(q)
print(y)

tensor([1., 2., 3., 4.], dtype=torch.float64)


In [28]:
print(q.dtype)
print(y.dtype)

float64
torch.float64


In [30]:
#convert the PyTorch tensors to NumPy 
a=y.numpy()
print(a)
print(a.dtype)


[1. 2. 3. 4.]
float64


#Pytorch instead of NumPy is mainly for two reasons:

* **AutoGrad**
The ability to compute gradients for tensor operations is a powerful ability that is essential for training neural networks and perform backpropagation.

* **GPU Support**: 
While working with massive datasets and large models, PyTorch tensor operations are carried out in Graphical Processing Units (GPUs), which will reduce the amount of time takes by ordinary CPUs by 40x to 50x.


Hence PyTorch is a very powerful Deep learning library widely used in the research and development community for its expressivity and pythonic nature.