<a href="https://colab.research.google.com/github/ENG19CS0334-TEJAAL-M/DL_Assignment/blob/main/lab_DEEP_LEARNING_PROGRAMS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical 
X = [[30],[40],[50],[60],[20],[10],[70]]
y = [0,1,1,1,0,0,1]
model = Sequential()
model.add(Dense(500, activation='relu', input_dim=1))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])
model.fit(X,y, epochs=100)
X_marks=[[20]]
print(model.predict(X_marks))


In [ ]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
x = [[4],[5],[6],[7],[8],[9],[10]]
y = [8, 10 , 12, 14, 16, 18, 20]
# Define model
model = Sequential()
model.add(Dense(1000, input_dim=1, activation= "relu"))
model.add(Dense(1000, activation= "relu"))
model.add(Dense(50, activation= "relu"))
model.add(Dense(1))
#model.summary() 
#Print model Summarymodel.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
model.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
model.fit(x,y,epochs=200)
x=[[12.0]]
print(model.predict(x))

Epoch 1/200
1/1 [==============================] - 1s 775ms/step - loss: 202.1974 - mean_squared_error: 202.1974
Epoch 2/200
1/1 [==============================] - 0s 15ms/step - loss: 159.0827 - mean_squared_error: 159.0827
Epoch 3/200
1/1 [==============================] - 0s 12ms/step - loss: 121.1263 - mean_squared_error: 121.1263
Epoch 4/200
1/1 [==============================] - 0s 12ms/step - loss: 86.6697 - mean_squared_error: 86.6697
Epoch 5/200
1/1 [==============================] - 0s 17ms/step - loss: 55.3303 - mean_squared_error: 55.3303
Epoch 6/200
1/1 [==============================] - 0s 15ms/step - loss: 28.4312 - mean_squared_error: 28.4312
Epoch 7/200
1/1 [==============================] - 0s 16ms/step - loss: 8.8892 - mean_squared_error: 8.8892
Epoch 8/200
1/1 [==============================] - 0s 16ms/step - loss: 0.2110 - mean_squared_error: 0.2110
Epoch 9/200
1/1 [==============================] - 0s 18ms/step - loss: 4.2620 - mean_squared_error: 4.2620
Epoch 10/

In [ ]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.utils import to_categorical
#from keras.utils import to_categorical 
X = [[30],[40],[50],[60],[20],[10],[70]]
y = [0,1,1,1,0,0,1]
model = Sequential()
model.add(Dense(500, activation='relu', input_dim=1))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])
model.fit(X,y, epochs=100)
X_marks=[[20]]
print(model.predict(X_marks))

In [ ]:
#01/09/21
#Linear regression with model accuracy
#import modules
import warnings
import pandas as pd
from sklearn import model_selection
import numpy as np
import sklearn
from sklearn import linear_model
X=[[1.0],[2.0],[3],[4.0],[5.0],[6.0],[7.0],[8.0],[9.0],[10.0]]
y=[2,4,6,8,10,12, 14, 16,18, 22]
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.5, random_state=7)
print("Training Features", X_train);
print("Training Labels",y_train);
print("Testing Data",X_test);
print("Testing Data",y_test)
reg=linear_model.LinearRegression()
reg.fit(X_train,y_train)
#accuracy on test set
result = reg.score(X_test, y_test)
print("Accuracy - test set: %.2f%%" % (result*100.0))
X_height=[[12.0]]
print(reg.predict(X_test))

Training Features [[10.0], [8.0], [4.0], [7.0], [5.0]]
Training Labels [22, 16, 8, 14, 10]
Testing Data [[9.0], [6.0], [1.0], [3], [2.0]]
Testing Data [18, 12, 2, 6, 4]
Accuracy - test set: 97.71%
[19.01754386 12.1754386   0.77192982  5.33333333  3.05263158]


In [ ]:
#same program as before with more accuracy
#import modules
import warnings
import pandas as pd
from sklearn import model_selection
import numpy as np
import sklearn
from sklearn import linear_model
X=[[4.0],[5.0],[6.0],[7.0],[8.0],[9.0],[10.0]]
y=[  8, 10 , 12, 14, 16, 18, 20]
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3, random_state=7)
print("Training Features", X_train);print("Training Labels",y_train);print("Training Data",X_test);print("Testing Data",y_test)
reg=linear_model.LinearRegression()
reg.fit(X_train,y_train)
#accuracy on test set
result = reg.score(X_test, y_test)
print("Accuracy - test set: %.2f%%" % (result*100.0))
X_height=[[12.0]]
print(reg.predict(X_test))

Training Features [[10.0], [7.0], [5.0], [8.0]]
Training Labels [20, 14, 10, 16]
Training Data [[6.0], [9.0], [4.0]]
Testing Data [12, 18, 8]
Accuracy - test set: 100.00%
[12. 18.  8.]


In [ ]:
#naive based algorithm
#06/09/21
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("Naive-Bayes-Classifier-Data.csv")
print(df)
df.head()
x=df.drop('diabetes',axis=1)
y=df['diabetes']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)
model=GaussianNB()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred

     glucose  bloodpressure  diabetes
0         40             85         0
1         40             92         0
2         45             63         1
3         45             80         0
4         40             73         1
..       ...            ...       ...
990       45             87         0
991       40             83         0
992       40             83         0
993       40             60         1
994       45             82         0

[995 rows x 3 columns]


array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0])

In [ ]:
#linear regression and logisitc regression difference in ml and  dl
#ml logistic regression
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression
X = [[30],[40],[50],[60],[20],[10],[70]]
y = [0,1,1,1,0,0,1]
classifier = LogisticRegression()
classifier.fit(X,y)
X_marks=[[20]]
print(classifier.predict(X_marks))

[0]


In [ ]:
#ml linear regression
import numpy as np
import sklearn
from sklearn import linear_model
height=[[4.0],[5.0],[6.0],[7.0],[8.0],[9.0],[10.0]]
weight=[  8, 10 , 12, 14, 16, 18, 20]
reg=linear_model.LinearRegression()
reg.fit(height,weight)
X_height=[[12.0]]
print(reg.predict(X_height))

[24.]


In [ ]:
#dl linear regression
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
x = [[4],[5],[6],[7],[8],[9],[10]]
y = [8, 10 , 12, 14, 16, 18, 20]
# Define model
model = Sequential()
model.add(Dense(1000, input_dim=1, activation= "relu"))
model.add(Dense(1000, activation= "relu"))
model.add(Dense(50, activation= "relu"))
model.add(Dense(1))
#model.summary() #Print model Summarymodel.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
model.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
model.fit(x,y,epochs=200)
x=[[12.0]]
print(model.predict(x))

Epoch 1/200
1/1 [==============================] - 1s 950ms/step - loss: 207.5196 - mean_squared_error: 207.5196
Epoch 2/200
1/1 [==============================] - 0s 18ms/step - loss: 146.5755 - mean_squared_error: 146.5755
Epoch 3/200
1/1 [==============================] - 0s 19ms/step - loss: 98.5235 - mean_squared_error: 98.5235
Epoch 4/200
1/1 [==============================] - 0s 14ms/step - loss: 56.3669 - mean_squared_error: 56.3669
Epoch 5/200
1/1 [==============================] - 0s 24ms/step - loss: 23.7187 - mean_squared_error: 23.7187
Epoch 6/200
1/1 [==============================] - 0s 17ms/step - loss: 4.1020 - mean_squared_error: 4.1020
Epoch 7/200
1/1 [==============================] - 0s 12ms/step - loss: 0.9085 - mean_squared_error: 0.9085
Epoch 8/200
1/1 [==============================] - 0s 18ms/step - loss: 12.9137 - mean_squared_error: 12.9137
Epoch 9/200
1/1 [==============================] - 0s 18ms/step - loss: 27.3837 - mean_squared_error: 27.3837
Epoch 10/

In [ ]:
import socket
#s//server scocket
s=socket.socket()
#tcp
print("Socket created")
#make server socket
#to bind port number

s.bind(('localhost',9999))
#ip adress ,port number
s.listen(1)
print('waiting for connections')
#while loop 

while True:
    c,addr=s.accept()
    #gives client socket and returns the address of client
    print("Connected with",addr)
    c.send(bytes("Welcome to DSU",'utf-8'))
    c.close()

Socket created
waiting for connections


KeyboardInterrupt: ignored

In [ ]:
#dl in logistic regression or classification
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical 
X = [[30],[40],[50],[60],[20],[10],[70]]
y = [0,1,1,1,0,0,1]
model = Sequential()
model.add(Dense(500, activation='relu', input_dim=1))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])
model.fit(X,y, epochs=100)
X_marks=[[20]]
print(model.predict(X_marks))

ImportError: ignored